language: node_js
node_js:
  - 16
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed justin8790/udagram-api-feed:v1.3
  - docker tag udagram-api-user justin8790/udagram-api-user:v1.3
  - docker tag udagram-frontend justin8790/udagram-frontend:v1.3
  - docker tag udagram-reverseproxy justin8790/udagram-reverseproxy:v1.3
  # Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push justin8790/udagram-api-feed:v1.3
  - docker push justin8790/udagram-api-user:v1.3
  - docker push justin8790/udagram-frontend:v1.3
  - docker push justin8790/udagram-reverseproxy:v1.3